[general]
; General settings for res_pjsip

[transport-udp]
; Define UDP transport for SIP
type=transport
protocol=udp
bind=0.0.0.0

[xxx-endpoint]
; Define SIP endpoint
type=endpoint
context=my-context ; Context for inbound calls (adjust as needed)
disallow=all
allow=ulaw ; Allow only ulaw codec, adjust as needed
auth=xxx-auth ; Authentication configuration for this endpoint
aors=xxx-aor ; Address of record configuration for this endpoint

[xxx-auth]
; Define authentication
type=auth
auth_type=userpass
username=xxx ; Username for authentication
password=xxx ; Password for authentication
realm=asterisk ; Realm used for authentication challenges

[xxx-aor]
; Define address of record
type=aor
max_contacts=1

