name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: jsipdialer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build with Maven
        run: mvn -Pnative package
     - name: Install UPX
       shell: bash
       run: |
         if [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
           brew install upx
         elif [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
           sudo apt-get update && sudo apt-get install -y upx
         elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
           choco install upx -y
         fi
     - name: Pack/compress binary
       run: |
          upx target/com.github.pfichtner.jsipdial.sipclientmain*
     - name: Upload binary
       uses: actions/upload-artifact@v2
       with:
         name: jsipdialer-${{ matrix.os }}
         path: target/com.github.pfichtner.jsipdial.sipclientmain*

