name: GraalVM Native Image builds

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: jsipdialer on ${{ matrix.os }}
    runs-on: ${{ matrix.os == 'darwin' && 'macos-latest' || matrix.os == 'linux' && 'ubuntu-latest' || matrix.os == 'windows' && 'windows-latest' }}
    strategy:
      matrix:
        os: [linux]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Build with Maven
        run: mvn verify
      - name: Install UPX
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == 'linux' ]]; then
            command -v upx || sudo apt-get update && sudo apt-get install -y upx
          elif [[ "${{ matrix.os }}" == 'darwin' ]]; then
            brew install upx
          elif [[ "${{ matrix.os }}" == 'windows' ]]; then
            choco install upx -y
          fi
      - name: Pack/compress binary
        run: |
           find target/ -type f -executable -exec upx {} +
      - name: Compress and move files
        run: |
          mkdir -p publish-artifacts
          find target -type f -executable -print0 | tar --null -czf "publish-artifacts/jsipdialer-${{ matrix.os }}.tar.gz" --files-from=-
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifacts-${{ matrix.os }}
          path: "publish-artifacts/*"

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "publish-artifacts*/*"
          makeLatest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

