name: Monthly Ubuntu Version Check

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check-ubuntu-version:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Ubuntu version
        run: |
          VERSION=$(lsb_release -r | awk '{print $2}')
          if [[ "$VERSION" == "24.04" ]]; then
            echo "Error: The runner is using Ubuntu $VERSION, please update .github/workflows/maven.yml and change ubuntu-24.04 to ubuntu-latest and delete this workflow"
            exit 1
          else
            echo "The runner is using the correct Ubuntu version: $VERSION"
          fi

